# Lord of the Rings — fan-made tribute game, 2012 (ASL 520, Quest 5.2.4515).
# No published walkthrough exists — derived from game source (game.aslx).
# _editorstyle=gamebook: commands are PAGE NAMES (the stringdictionary options'
# KEYS, not the displayed link text — e.g. type "The Prancing Pony", not "Go to
# the Prancing Pony"). Zero `finish()` calls in the source; it is a free-roam
# hub map covering the whole of Middle-earth (Hobbiton/Buckland/Bree/Rivendell/
# Moria/Lothlorien/Mirkwood/Rohan/Gondor/Mordor/the Lonely Mountain) with no
# closing page at all — every room loops back, so there is no terminal state
# to reach. This 173-step script is a COMPLETE TOUR: every reachable room and
# every "Talk to X" NPC dialogue, generated by BFS over the page graph, ending
# on an arbitrary stop (The Witch King) once full coverage is reached.
# Character creation (Intro: gender, then race) is a one-way choice with no
# path back to Intro, so the three untaken race branches (Dwarf/Man/Elf — this
# script takes Male/Hobbit) and the untaken Female branch are inherently
# unvisitable in a single playthrough, same as any other IF opening choice;
# they carry no unique content beyond a one-line flavour blurb and a picture.
# Author bug: Orthanc/Saruman is unreachable — no page in the source has an
# option KEY of "Orthanc" (Isengard's options are Moria/Fangorn Forest/Helms
# Deep only), even though the Orthanc object itself has a working "Leave"
# option back to Isengard. Confirmed via full source parse (no `<options>`
# anywhere lists "Orthanc" as a key). errors=0.
Male
Hobbit
Home
Bree
The Prancing Pony
Aragorn
The Prancing Pony
Gandalf
The Prancing Pony
Barliman
The Prancing Pony
Bree
The Old Forest
Buckland
Brandy Hall
Merry
Brandy Hall
Pippin
Brandy Hall
Buckland
Hobbiton
The Green Dragon
Rosie
The Green Dragon
Frodo
The Green Dragon
Sam
The Green Dragon
Gaffer
The Green Dragon
Bilbo
The Green Dragon
Hobbiton
Mithlond
Cirdan
Mithlond
Hobbiton
Buckland
The Old Forest
The House of Tom Bombadil
Tom
The House of Tom Bombadil
Goldberry
The House of Tom Bombadil
The Old Forest
Bree
Amon Sul
Rivendell
The House of Elrond
Elrond
The House of Elrond
Arwen
The House of Elrond
Elladan
The House of Elrond
Elrohir
The House of Elrond
Glorfindel
The House of Elrond
Erestor
The House of Elrond
Lindir
The House of Elrond
Rivendell
The Misty Mountains
The Main Cave
Gimli
The Main Cave
Gloin
The Main Cave
The Misty Mountains
Mirkwood
The Cave of Thranduil
Thranduil
The Cave of Thranduil
Legolas
The Cave of Thranduil
Galion
The Cave of Thranduil
Mirkwood
Caras Galadhon
The Glade of Galadriel
Galadriel
The Glade of Galadriel
Celeborn
The Glade of Galadriel
Haldir
The Glade of Galadriel
Rumil
The Glade of Galadriel
Orophin
The Glade of Galadriel
Caras Galadhon
Moria
The Chamber of Mazarbul
Moria
Isengard
Fangorn Forest
Edoras
The Golden Hall
Theoden
The Golden Hall
Theodred
The Golden Hall
Grima
The Golden Hall
Eomer
The Golden Hall
Eowyn
The Golden Hall
Hama
The Golden Hall
Haleth
The Golden Hall
Gamling
The Golden Hall
Edoras
Helms Deep
Edoras
Minas Tirith
The Citadel
Denethor
The Citadel
Boromir
The Citadel
Beregond
The Citadel
Minas Tirith
Osgiliath
Minas Morgul
Shelobs Lair
Shelob
Shelobs Lair
Cirith Ungol
Mount Doom
Henneth Annun
The Dead Marshes
Morannon
The Mouth of Sauron
Morannon
Mount Doom
Barad Dur
Sauron
Barad Dur
Mount Doom
Henneth Annun
Faramir
Henneth Annun
Minas Morgul
The Nazgul
Minas Morgul
Osgiliath
Minas Tirith
Edoras
Dunharrow
The Paths of the Dead
The King of the Dead
The Paths of the Dead
Dunharrow
Edoras
Fangorn Forest
Treebeard
Fangorn Forest
Caras Galadhon
Mirkwood
The Lonely Mountain
Smaug
The Lonely Mountain
Mirkwood
The Misty Mountains
Rivendell
Angmar
The Witch King
