# Fishvale (v580, fishing-economy sim): bounded tour, not a solve. Depth-first walk of the starting Civilization area (Tent, Fishvale shop, Train Station, Coffee Shop, Flower Garden, Riverbank, ...).
# The only `finish` is the custom `quit` command; progress is gold/fishing-level grind. Mountain Tracks' north and east exits are locked until later, so they are not walked.
south
south
east
east
north
north
west
west
east
east
south
south
west
west
down
north
north
east
east
south
south
west
south
north
east
north
north
west
west
north
south
south
south
up
north
north
